from_latest_tag = false
ignore_merge_commits = true
tag_prefix = "v"
branch_whitelist = ["no_bump_allowed"]
pre_bump_hooks = [
  "echo Bumping with cog is not allowed. Use release-plz instead...",
  "exit 1",
]
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks.commit-msg]
script = """#!/bin/sh
set -e

echo "[ just cargo-fmt-check ]"
just cargo-fmt-check

echo "[ typos ]"
typos

echo "[ typos $1 ]"
typos $1

echo "[ just machete ]"
just machete

echo "[ just deny-licenses ]"
just deny-licenses

echo "[ cog verify ]"
cog verify --file $1
"""

# Configure the generation of the changelog.
[changelog]

[commit_types]

[bump_profiles]
